name:                pkr-tools
version:             0.1.0.0
github:              "reubensammut/pkr-tools"
license:             BSD3
author:              "Reuben Sammut"
maintainer:          "reubensammut@gmail.com"
copyright:           "2018 Reuben Sammut"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/reubensammut/pkr-tools#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal

library:
  source-dirs: src

executables:
  pkr-tools-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pkr-tools

tests:
  pkr-tools-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pkr-tools
